# Generated by Django 4.1.7 on 2023-03-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('week5', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission5',
            old_name='chocies',
            new_name='choices',
        ),
        migrations.RemoveField(
            model_name='question5',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='question5',
            name='user',
        ),
        migrations.AddField(
            model_name='choice5',
            name='answer',
            field=models.CharField(default='write your answer', max_length=200),
        ),
        migrations.AddField(
            model_name='question5',
            name='course',
            field=models.ManyToManyField(to='week5.course5'),
        ),
        migrations.AlterField(
            model_name='choice5',
            name='choice_text',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=200),
        ),
        migrations.AlterField(
            model_name='question5',
            name='grade',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='question5',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='examGrades5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='week5.course5')),
                ('exam_answer', models.ManyToManyField(to='week5.choice5')),
                ('exam_question', models.ManyToManyField(to='week5.question5')),
            ],
        ),
    ]
